spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs

slack:
  url: https://hooks.slack.com/services/{hook-url}